# Test the handling of functions that return errors

# call a bad function
! errlogmatch 'recvJSONMsg:.*got error whilst handling Bad'
vim -bang expr 'Bad()'
! stdout .+
[vim] stderr '^\Qfailed to expr(Bad()) in Vim: Caught ''got error whilst handling Bad: this is a bad function''\E'
[gvim] stderr '^\Qfailed to expr(Bad()) in Vim: Caught ''got error whilst handling Bad: this is a bad function''\E'
[neovim] stderr '^\Qnvim:nvim_eval exception: Vim(let):this is a bad function\E'

[vim] errlogmatch 'recvJSONMsg:.*got error whilst handling Bad'
[gvim] errlogmatch 'recvJSONMsg:.*got error whilst handling Bad'

[vim] ! errlogmatch 'recvJSONMsg:.*got error whilst handling Bad'
[gvim] ! errlogmatch 'recvJSONMsg:.*got error whilst handling Bad'

[vim] errlogmatch -start 'recvJSONMsg:.*got error whilst handling Bad'
[gvim] errlogmatch -start 'recvJSONMsg:.*got error whilst handling Bad'
